parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_pgsql'
                server_version: '10.11'
                charset: utf8
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                url: '%env(resolve:DATABASE_URL)%'
    orm:
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Reservation:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Reservation/Domain/Entity'
                        prefix: App\Reservation\Entity
                    Holder:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Reservation/Domain/Entity'
                        prefix: App\Reservation\Entity
                    Room:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Reservation/Domain/Entity'
                        prefix: App\Reservation\Entity