version: '3.7'
services:
  booking_php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['.:/var/www/booking']
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    volumes: ['.:/var/www/booking']
  booking_db:
    image: postgres:10.11-alpine
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking_db
      PGDATA: /var/lib/postgresql/data/pgdata
      DOMAIN_NAME: default:db-booking.local